// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/Chart.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Heading: typeof import('./src/components/Heading.vue')['default']
    MapBox: typeof import('./src/components/MapBox.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
